server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/my_electronic_card
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp